package com.myspace.customeronboarding;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class appData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.Boolean customerExistAccount;
	private java.lang.Boolean customerAmlCleared;
	private java.lang.Boolean needSignatories;
	private java.lang.Boolean branchSupervisorAmendment;
	private java.lang.Boolean branchSupervisorApprove;
	private java.lang.Boolean signatoriesExistAccount;
	private java.lang.Boolean signatoriesAmlCleared;
	private java.lang.Boolean complianceApprove;
	private java.lang.Boolean makerMissingDocs;
	private java.lang.Boolean checkerApprove;

	@org.kie.api.definition.type.Label(value = "Customer Main Data")
	private com.myspace.customeronboarding.CustomerData customerMainData;

	@org.kie.api.definition.type.Label(value = "Signatory Main Data")
	private com.myspace.customeronboarding.CustomerData signatoryMainData;

	public appData() {
	}

	public java.lang.Boolean getCustomerExistAccount() {
		return this.customerExistAccount;
	}

	public void setCustomerExistAccount(java.lang.Boolean customerExistAccount) {
		this.customerExistAccount = customerExistAccount;
	}

	public java.lang.Boolean getCustomerAmlCleared() {
		return this.customerAmlCleared;
	}

	public void setCustomerAmlCleared(java.lang.Boolean customerAmlCleared) {
		this.customerAmlCleared = customerAmlCleared;
	}

	public java.lang.Boolean getNeedSignatories() {
		return this.needSignatories;
	}

	public void setNeedSignatories(java.lang.Boolean needSignatories) {
		this.needSignatories = needSignatories;
	}

	public java.lang.Boolean getBranchSupervisorAmendment() {
		return this.branchSupervisorAmendment;
	}

	public void setBranchSupervisorAmendment(
			java.lang.Boolean branchSupervisorAmendment) {
		this.branchSupervisorAmendment = branchSupervisorAmendment;
	}

	public java.lang.Boolean getBranchSupervisorApprove() {
		return this.branchSupervisorApprove;
	}

	public void setBranchSupervisorApprove(
			java.lang.Boolean branchSupervisorApprove) {
		this.branchSupervisorApprove = branchSupervisorApprove;
	}

	public java.lang.Boolean getSignatoriesExistAccount() {
		return this.signatoriesExistAccount;
	}

	public void setSignatoriesExistAccount(
			java.lang.Boolean signatoriesExistAccount) {
		this.signatoriesExistAccount = signatoriesExistAccount;
	}

	public java.lang.Boolean getSignatoriesAmlCleared() {
		return this.signatoriesAmlCleared;
	}

	public void setSignatoriesAmlCleared(java.lang.Boolean signatoriesAmlCleared) {
		this.signatoriesAmlCleared = signatoriesAmlCleared;
	}

	public java.lang.Boolean getComplianceApprove() {
		return this.complianceApprove;
	}

	public void setComplianceApprove(java.lang.Boolean complianceApprove) {
		this.complianceApprove = complianceApprove;
	}

	public java.lang.Boolean getMakerMissingDocs() {
		return this.makerMissingDocs;
	}

	public void setMakerMissingDocs(java.lang.Boolean makerMissingDocs) {
		this.makerMissingDocs = makerMissingDocs;
	}

	public java.lang.Boolean getCheckerApprove() {
		return this.checkerApprove;
	}

	public void setCheckerApprove(java.lang.Boolean checkerApprove) {
		this.checkerApprove = checkerApprove;
	}

	public com.myspace.customeronboarding.CustomerData getCustomerMainData() {
		return this.customerMainData;
	}

	public void setCustomerMainData(
			com.myspace.customeronboarding.CustomerData customerMainData) {
		this.customerMainData = customerMainData;
	}

	public com.myspace.customeronboarding.CustomerData getSignatoryMainData() {
		return this.signatoryMainData;
	}

	public void setSignatoryMainData(
			com.myspace.customeronboarding.CustomerData signatoryMainData) {
		this.signatoryMainData = signatoryMainData;
	}

	public appData(java.lang.Boolean customerExistAccount,
			java.lang.Boolean customerAmlCleared,
			java.lang.Boolean needSignatories,
			java.lang.Boolean branchSupervisorAmendment,
			java.lang.Boolean branchSupervisorApprove,
			java.lang.Boolean signatoriesExistAccount,
			java.lang.Boolean signatoriesAmlCleared,
			java.lang.Boolean complianceApprove,
			java.lang.Boolean makerMissingDocs,
			java.lang.Boolean checkerApprove,
			com.myspace.customeronboarding.CustomerData customerMainData,
			com.myspace.customeronboarding.CustomerData signatoryMainData) {
		this.customerExistAccount = customerExistAccount;
		this.customerAmlCleared = customerAmlCleared;
		this.needSignatories = needSignatories;
		this.branchSupervisorAmendment = branchSupervisorAmendment;
		this.branchSupervisorApprove = branchSupervisorApprove;
		this.signatoriesExistAccount = signatoriesExistAccount;
		this.signatoriesAmlCleared = signatoriesAmlCleared;
		this.complianceApprove = complianceApprove;
		this.makerMissingDocs = makerMissingDocs;
		this.checkerApprove = checkerApprove;
		this.customerMainData = customerMainData;
		this.signatoryMainData = signatoryMainData;
	}

}