package com.myspace.customeronboarding;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CustomerData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("ID Type")
	private java.lang.String idType;
	@org.kie.api.definition.type.Label("ID Number")
	private java.lang.String idNumber;
	@org.kie.api.definition.type.Label("Full Name Arabic")
	private java.lang.String fullNameAr;

	@org.kie.api.definition.type.Label("Full Name English")
	private java.lang.String fullNameEn;

	@org.kie.api.definition.type.Label("Place Off Birth")
	private java.lang.String placeOffBirth;

	@org.kie.api.definition.type.Label("Date Off Birth")
	private Date dateOffBirth;

	public CustomerData() {
	}

	public java.lang.String getIdType() {
		return this.idType;
	}

	public void setIdType(java.lang.String idType) {
		this.idType = idType;
	}

	public java.lang.String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(java.lang.String idNumber) {
		this.idNumber = idNumber;
	}

	public java.lang.String getFullNameAr() {
		return this.fullNameAr;
	}

	public void setFullNameAr(java.lang.String fullNameAr) {
		this.fullNameAr = fullNameAr;
	}

	public java.lang.String getFullNameEn() {
		return this.fullNameEn;
	}

	public void setFullNameEn(java.lang.String fullNameEn) {
		this.fullNameEn = fullNameEn;
	}

	public java.lang.String getPlaceOffBirth() {
		return this.placeOffBirth;
	}

	public void setPlaceOffBirth(java.lang.String placeOffBirth) {
		this.placeOffBirth = placeOffBirth;
	}

	public java.util.Date getDateOffBirth() {
		return this.dateOffBirth;
	}

	public void setDateOffBirth(java.util.Date dateOffBirth) {
		this.dateOffBirth = dateOffBirth;
	}

	public CustomerData(java.lang.String idType, java.lang.String idNumber,
			java.lang.String fullNameAr, java.lang.String fullNameEn,
			java.lang.String placeOffBirth, java.util.Date dateOffBirth) {
		this.idType = idType;
		this.idNumber = idNumber;
		this.fullNameAr = fullNameAr;
		this.fullNameEn = fullNameEn;
		this.placeOffBirth = placeOffBirth;
		this.dateOffBirth = dateOffBirth;
	}

}